# Generated by Django 4.0.3 on 2022-04-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_alter_post_author_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
