# Generated by Django 4.0.2 on 2022-03-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_head_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='blog/files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='head_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/%Y/%m/%d/'),
        ),
    ]
